//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTest.ServicePerson {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePerson.IServicePerson")]
    public interface IServicePerson {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePerson/AddPerson", ReplyAction="http://tempuri.org/IServicePerson/AddPersonResponse")]
        void AddPerson(DataAccessObjects.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePerson/AddPerson", ReplyAction="http://tempuri.org/IServicePerson/AddPersonResponse")]
        System.Threading.Tasks.Task AddPersonAsync(DataAccessObjects.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePerson/RemovePerson", ReplyAction="http://tempuri.org/IServicePerson/RemovePersonResponse")]
        void RemovePerson(DataAccessObjects.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePerson/RemovePerson", ReplyAction="http://tempuri.org/IServicePerson/RemovePersonResponse")]
        System.Threading.Tasks.Task RemovePersonAsync(DataAccessObjects.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePerson/GetPersonList", ReplyAction="http://tempuri.org/IServicePerson/GetPersonListResponse")]
        DataAccessObjects.Person[] GetPersonList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePerson/GetPersonList", ReplyAction="http://tempuri.org/IServicePerson/GetPersonListResponse")]
        System.Threading.Tasks.Task<DataAccessObjects.Person[]> GetPersonListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePersonChannel : WebApplicationTest.ServicePerson.IServicePerson, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePersonClient : System.ServiceModel.ClientBase<WebApplicationTest.ServicePerson.IServicePerson>, WebApplicationTest.ServicePerson.IServicePerson {
        
        public ServicePersonClient() {
        }
        
        public ServicePersonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePersonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePersonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePersonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddPerson(DataAccessObjects.Person person) {
            base.Channel.AddPerson(person);
        }
        
        public System.Threading.Tasks.Task AddPersonAsync(DataAccessObjects.Person person) {
            return base.Channel.AddPersonAsync(person);
        }
        
        public void RemovePerson(DataAccessObjects.Person person) {
            base.Channel.RemovePerson(person);
        }
        
        public System.Threading.Tasks.Task RemovePersonAsync(DataAccessObjects.Person person) {
            return base.Channel.RemovePersonAsync(person);
        }
        
        public DataAccessObjects.Person[] GetPersonList() {
            return base.Channel.GetPersonList();
        }
        
        public System.Threading.Tasks.Task<DataAccessObjects.Person[]> GetPersonListAsync() {
            return base.Channel.GetPersonListAsync();
        }
    }
}
