//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplicationTest.ServiceReferenceAddition {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFTestWebService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAddition.IServiceAddition")]
    public interface IServiceAddition {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAddition/GetData", ReplyAction="http://tempuri.org/IServiceAddition/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAddition/GetData", ReplyAction="http://tempuri.org/IServiceAddition/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAddition/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceAddition/GetDataUsingDataContractResponse")]
        ConsoleApplicationTest.ServiceReferenceAddition.CompositeType GetDataUsingDataContract(ConsoleApplicationTest.ServiceReferenceAddition.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAddition/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceAddition/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ConsoleApplicationTest.ServiceReferenceAddition.CompositeType> GetDataUsingDataContractAsync(ConsoleApplicationTest.ServiceReferenceAddition.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAddition/Addition", ReplyAction="http://tempuri.org/IServiceAddition/AdditionResponse")]
        int Addition(int value1, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAddition/Addition", ReplyAction="http://tempuri.org/IServiceAddition/AdditionResponse")]
        System.Threading.Tasks.Task<int> AdditionAsync(int value1, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAddition/AddName", ReplyAction="http://tempuri.org/IServiceAddition/AddNameResponse")]
        void AddName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAddition/AddName", ReplyAction="http://tempuri.org/IServiceAddition/AddNameResponse")]
        System.Threading.Tasks.Task AddNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAddition/RemoveName", ReplyAction="http://tempuri.org/IServiceAddition/RemoveNameResponse")]
        void RemoveName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAddition/RemoveName", ReplyAction="http://tempuri.org/IServiceAddition/RemoveNameResponse")]
        System.Threading.Tasks.Task RemoveNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAddition/GenerateNameList", ReplyAction="http://tempuri.org/IServiceAddition/GenerateNameListResponse")]
        string[] GenerateNameList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAddition/GenerateNameList", ReplyAction="http://tempuri.org/IServiceAddition/GenerateNameListResponse")]
        System.Threading.Tasks.Task<string[]> GenerateNameListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAdditionChannel : ConsoleApplicationTest.ServiceReferenceAddition.IServiceAddition, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAdditionClient : System.ServiceModel.ClientBase<ConsoleApplicationTest.ServiceReferenceAddition.IServiceAddition>, ConsoleApplicationTest.ServiceReferenceAddition.IServiceAddition {
        
        public ServiceAdditionClient() {
        }
        
        public ServiceAdditionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAdditionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAdditionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAdditionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ConsoleApplicationTest.ServiceReferenceAddition.CompositeType GetDataUsingDataContract(ConsoleApplicationTest.ServiceReferenceAddition.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplicationTest.ServiceReferenceAddition.CompositeType> GetDataUsingDataContractAsync(ConsoleApplicationTest.ServiceReferenceAddition.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public int Addition(int value1, int value2) {
            return base.Channel.Addition(value1, value2);
        }
        
        public System.Threading.Tasks.Task<int> AdditionAsync(int value1, int value2) {
            return base.Channel.AdditionAsync(value1, value2);
        }
        
        public void AddName(string name) {
            base.Channel.AddName(name);
        }
        
        public System.Threading.Tasks.Task AddNameAsync(string name) {
            return base.Channel.AddNameAsync(name);
        }
        
        public void RemoveName(string name) {
            base.Channel.RemoveName(name);
        }
        
        public System.Threading.Tasks.Task RemoveNameAsync(string name) {
            return base.Channel.RemoveNameAsync(name);
        }
        
        public string[] GenerateNameList() {
            return base.Channel.GenerateNameList();
        }
        
        public System.Threading.Tasks.Task<string[]> GenerateNameListAsync() {
            return base.Channel.GenerateNameListAsync();
        }
    }
}
